url: https://gjazeron.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /    # place folder name if the site is served in a subfolder

title: Guilhem Jazeron
description: PhD student in symmetric cryptography in the COSMIQ team at INRIA Paris (France)

remote_theme: pages-themes/leap-day@v0.2.0