url: https://gjazeron.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /    # place folder name if the site is served in a subfolder

remote_theme: pages-themes/cayman@v0.2.0

